name: Deploy Latest Release to Kinsta

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest release archive
        run: |
          curl -L "https://github.com/CapWebSolutions/wre-mai-achieve/archive/refs/tags/${{ github.event.release.tag_name }}.zip" -o wre-mai-achieve.zip

      - name: Upload files to Kinsta via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.KINSTA_HOST }}
          username: ${{ secrets.KINSTA_USERNAME }}
          key: ${{ secrets.KINSTA_SSH_KEY }}
          port: 22
          source: wre-mai-achieve.zip
          target: /www/wesselrealestate_425/public/wp-content/themes

      - name: Unpack and set permissions on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KINSTA_HOST }}
          username: ${{ secrets.KINSTA_USERNAME }}
          key: ${{ secrets.KINSTA_SSH_KEY }}
          port: 22
          script: |
            cd /www/wesselrealestate_425/public/wp-content/themes
            unzip -o wre-mai-achieve.zip
            # Copy contents from wre-mai-achieve-${{ github.event.release.tag_name }} to theme directory
            cp -rf wre-mai-achieve-${{ github.event.release.tag_name }}/* mai-achieve/
            #rm -rf wre-mai-achieve-${{ github.event.release.tag_name }}
            #rm wre-mai-achieve.zip
            #chown -R www-data:www-data /www/wesselrealestate_425/public/wp-content/themes
